# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{triumph}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Adam Bray}]
  s.date = %q{2011-07-15}
  s.description = %q{Triumph makes it easy to add achievements to your app, even dynamically at runtime.}
  s.email = %q{adam.bray@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/.DS_Store",
    "lib/achievements.rb",
    "lib/app/controllers/achievements_controller.rb",
    "lib/app/models/achievement.rb",
    "lib/app/models/completed_achievement.rb",
    "lib/app/views/achievements/index.html.erb",
    "lib/app/views/achievements/new.html.erb",
    "lib/db/.DS_Store",
    "lib/db/migrate/20110711040135_create_achievements.rb",
    "lib/db/migrate/20110712025245_create_completed_achievements.rb",
    "lib/db/migrate/20110712033351_create_achievement_conditions.rb",
    "lib/generators/.DS_Store",
    "lib/generators/achievement_observer/achievement_observer_generator.rb",
    "lib/generators/achievement_observer/templates/achievement_observer.rb",
    "lib/generators/triumph/.DS_Store",
    "lib/generators/triumph/triumph_generator.rb",
    "lib/tasks/triumph_tasks.rake",
    "lib/triumph.rb",
    "rails/init.rb",
    "test/helper.rb",
    "test/test_triumph.rb",
    "triumph.gemspec"
  ]
  s.homepage = %q{http://github.com/adambray/triumph}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Trimuph helps you add achievements to your app}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<rails3-generators>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<rails3-generators>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<rails3-generators>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.0"])
  end
end

